virtio_balloon: Add option mprotect to handle guest kernel cheat issue
QEMU virtio_balloon decreases the memory usage of VM depends on the
cooperation of the guest kernel.  If the guest kernel cheats with
the virtio_balloon, it can break the limit.

[1] is a Linux kernel with a cheat code.
This is an example in a VM with 1G memory 1CPU that use this kernel:
// Start VM.
// In the guest, use usemem(https://git.kernel.org/pub/scm/linux/kernel/git/wfg/vm-scalability.git)
// allocate 800M memory then the usage of VM will increase.
usemem 800m

// Check anon memory usage of QEMU in the host.
ps -e | grep qemu
67768 pts/5    00:00:02 qemu-system-x86
cat /proc/67768/status | grep RssAnon:
RssAnon:          994892 kB

// Connect to the monitor of QEMU and inflate the balloon 800M.
(qemu) device_add virtio-balloon-pci,id=balloon1
(qemu) info balloon
balloon: actual=1024
(qemu) balloon 224
(qemu) info balloon
balloon: actual=224

// Check anon memory usage of QEMU in the host again.
cat /proc/67768/status | grep RssAnon:
RssAnon:          175848 kB

// Use the cheat code inside the guest kernel to
// access the memory of the balloon.
cat /proc/virtio_balloon
204800

// The memory usage of QEMU increase back without deflation the balloon.
cat /proc/67768/status | grep RssAnon:
RssAnon:          995036 kB

This commit tries to handle the issue.
It set the address of balloon pages to cannot access with mprotect
when inflating the balloon and set it back when deflating the balloon.
When guest kernel cheat code tries to access the pages inside the balloon,
the host kernel will call handle_ept_violation-> tdp_page_fault to handle it.
tdp_page_fault will call hva_to_pfn to get PFN of the page.
hva_to_pfn_fast and hva_to_pfn_slow will check the VMA access permission.
Then change the VMA access permission can handle the issue.

This is an example in a VM with 1G memory 1CPU that use this kernel:
// Start VM.
// In the guest, use usemem(https://git.kernel.org/pub/scm/linux/kernel/git/wfg/vm-scalability.git)
// allocate 800M memory then the usage of VM will increase.
usemem 800m

// Connect to the monitor of QEMU and inflate the balloon 800M.
(qemu) device_add virtio-balloon-pci,id=balloon1,mprotect=on
(qemu) info balloon
balloon: actual=1024
(qemu) balloon 224
(qemu) info balloon
balloon: actual=224

// Use the cheat code inside the guest kernel to access the memory of balloon.
cat /proc/virtio_balloon
error: kvm run failed Bad address
RAX=000000000783c000 RBX=0000000000000000 RCX=ffff88803952bc00 RDX=ffff888000000000
RSI=ffffea00001e0f40 RDI=ffffea00001e0f48 RBP=ffff88803aac7180 RSP=ffffc90000207a70
R8 =ffff8880396af100 R9 =ffff88803a802700 R10=0000000000001000 R11=ffffffffffffffff
R12=ffff8880396af120 R13=0000000000000001 R14=ffffc90000207c60 R15=ffff88803aac7180
RIP=ffffffff81604aad RFL=00010206 [-----P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 0000000000000000 ffffffff 00c00000
CS =0010 0000000000000000 ffffffff 00a09b00 DPL=0 CS64 [-RA]
SS =0018 0000000000000000 ffffffff 00c09300 DPL=0 DS   [-WA]
DS =0000 0000000000000000 ffffffff 00c00000
FS =0000 0000000000bcd880 ffffffff 00c00000
GS =0000 ffff88803ec00000 ffffffff 00c00000
LDT=0000 0000000000000000 ffffffff 00c00000
TR =0040 fffffe0000003000 00004087 00008b00 DPL=0 TSS64-busy
GDT=     fffffe0000001000 0000007f
IDT=     fffffe0000000000 00000fff
CR0=80050033 CR2=00000000008a2260 CR3=00000000396b6004 CR4=00360ef0
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000fffe0ff0 DR7=0000000000000400
EFER=0000000000000d01
Code=05 72 5b e1 00 48 8b 15 7b 5b e1 00 48 c1 f8 06 48 c1 e0 0c <c6> 04 10 01 83 a9 a8 12 00 00 01 48 8b 46 08 83 c3 01 48 8d 50 f8 48 8d 46 08 49 35

This shows that the access is refused and QEMU stops.

[1] https://github.com/teawater/linux/tree/write_balloon

Signed-off-by: Hui Zhu <teawaterz@linux.alibaba.com>